const PokemonActionTypes = {
  FETCH_POKEMON_START: 'FETCH_POKEMON_START',
  FETCH_POKEMON_SUCCESS: 'FETCH_POKEMON_SUCCESS',
  FETCH_POKEMON_FAILURE: 'FETCH_POKEMON_FAILUER',
};

const CategoriesActionTypes = {
  FETCH_DATA_START: 'FETCH_DATA_START',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FAILURE: 'FETCH_DATA_FAILURE',
};

export { PokemonActionTypes, CategoriesActionTypes };
